### PR TITLE
All Instruction files in HTML Styled Format

### PR DESCRIPTION
**Pull request by pushkar72**
Its just helpful for my students because local machine cannot open instruction in md format

### CODE REVIEW

**Comment by ConcreteGannet** [comment]
With due respect to @pushkar72 , I suggest these shouldn't be added. That would create a second set of files to be maintained in parallel with the Markdown. Almost certainly there will be discrepancies between the two, and adding HTML would double the maintenance effort.

Rather than adding HTML files to the source, there should be a build task to generate more readable files from the Markdown. I would suggest generating PDF rather than HTML, but that's not all that important.

pandoc (pandoc.org) can generate PDF, HTML and others from Markdown. You could even generate *both* if you wanted to.

**Comment by seesharprun** [comment]
Have either of you viewed the **gh-pages** branch? This branch is the result of a manual build step and it generates HTML files.

They can be viewed here: <https://microsoftlearning.github.io/20532-DevelopingMicrosoftAzureSolutions/>

I'm working on improving that web page and making the build step automatic. To do this, I would need to update the build script to generate HTML based on a flag.

@pushkar72: Would this solve your need?

@ConcreteGannet: I will open up an issue in GitHub when I have time to work on this task

**Comment by ConcreteGannet** [comment]
Hi Sidney,

I wasn't aware of that branch. Looks fine to me. Making the build step automatic would be nice to have but I think it's low priority.

Thanks for all you work on this.

I have been saying for years that if the training materials were more accessible, trainers would maintain it for Microsoft. 20532 is an existence proof that I was right.

Cheers

Paul Foxworthy

**Comment by molenaar** [comment]
Other question? Do you share this knowless and solutions with other course writers? This would be very helpful for the 20533 course too. Seems like every repository has its own style and way of solving similar problems..it's the same Azure changing rapidly. It's the same way we have to deliver the course and let students practice.

Marcel

________________________________

**Comment by molenaar** [comment]
Looks great. Wasn't aware of it either.
Keep up the good work!

Marcel


________________________________

**Comment by seesharprun** [comment]
@molenaar: I will reach out and share some of the stuff we're doing in this repo and see if it will help the other repo maintainers.  You are right, each repo has it's own individual identity.

**Comment by seesharprun** [comment]
Let's take this conversation to Issue #132. I want to make sure we come to a consensus as a community before making a major change or accepting this PR. It's closed, but you have your branch in case we need to re-open it.

**Pull request closed without merging**
